name: CUDA Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cuda-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 

    steps:
      - name: Setup MSVC Developer Command Prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: '12.6.0'
          method: 'network'
          use-cache: false

      - name: Check CUDA Setup
        shell: bash -el {0}
        run: |
          echo "CUDA Path: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
          which nvcc
          nvcc --version
      
      - name: Configure and Build with CMake
        shell: bash -el {0}
        run: |
          mkdir build
          cd build
          cmake .. \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCUDAToolkit_ROOT=${{ steps.cuda-toolkit.outputs.CUDA_PATH }} \
            -DCMAKE_CUDA_COMPILER=${{ steps.cuda-toolkit.outputs.CUDA_PATH }}/bin/nvcc \
            -DBUILD_PYTHON=OFF
          cmake --build .
