name: Build cuda

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 0: get cuda toolkit
    - name: Install CUDA Toolkit
      id: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.23
      with:
        cuda: '12.6.0'
        method: 'network'

    # Step 0b print `which nvcc`
    - name: Print nvcc path
      shell: bash -el {0}
      run: |
        echo "PATH: $PATH"
        echo "CUDA_HOME: $CUDA_HOME"
        echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
        which nvcc
        nvcc --version
        echo "CUDA_PATH: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Micromamba
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        micromamba-version: latest
        init-shell: bash
        post-cleanup: all
    
    # Step 3: Configure and Build with CMake and Ninja
    - name: Configure and Build
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCUDAToolkit_ROOT=${{steps.cuda-toolkit.outputs.CUDA_PATH}} -DCMAKE_CUDA_COMPILER=${{ steps.cuda-toolkit.outputs.CUDA_PATH }}/bin/nvcc
        cmake --build .

    # Step 4: Install
    - name: Install
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        cd build
        cmake --install .

    # Step 5: Uninstall
    - name: Uninstall
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        cd build
        cmake --build . --target uninstall
