name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Micromamba
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        micromamba-version: latest
        init-shell: bash
        post-cleanup: all

    # Step 3: Configure and Build with CMake and Ninja
    - name: Configure and Build
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
        cmake --build .

    - name: Run Tests
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        cd build
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          ctest -C Debug --output-on-failure
        else
          ctest --output-on-failure
        fi


    # Step 5: Install
    - name: Install
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        cd build
        cmake --install .

    # Step 6: Uninstall
    - name: Uninstall
      shell: bash -el {0}
      run: |
        micromamba activate parallelproj_backend
        cd build
        cmake --build . --target uninstall
