name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Micromamba
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: bash powershell
        micromamba-version: latest
        post-cleanup: all

    # Step 3: Configure and Build with CMake and Ninja
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_INTERFACE=ON
        cmake --build .
      shell: bash
      if: runner.os != 'Windows'

    - name: Configure and Build (Windows)
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_INTERFACE=ON
        cmake --build .
      shell: powershell
      if: runner.os == 'Windows'

    # Step 4: Run Tests with CTest
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
      shell: bash
      if: runner.os != 'Windows'

    - name: Run Tests (Windows)
      run: |
        cd build
        ctest --output-on-failure
      shell: powershell
      if: runner.os == 'Windows'
